QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	['unemployed'] = {label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Freelancer', payment = 10}}},
    ['bus'] =        {label = 'Bus',      defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Driver',     payment = 50}}},
	['judge'] =      {label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Judge',      payment = 100}}},
	['lawyer'] =     {label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Associate',  payment = 50}}},
	['reporter'] =   {label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Journalist', payment = 50}}},
	['trucker'] =    {label = 'Trucker',  defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Driver',     payment = 50}}},
	['tow'] =        {label = 'Towing',   defaultDuty = true, type = "tow", offDutyPay = false, grades = {['0'] = {name = 'Driver',     payment = 50}}},
	['garbage'] =    {label = 'Garbage',  defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Collector',  payment = 50}}},
	['vineyard'] =   {label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Picker',     payment = 50}}},
	['hotdog'] =     {label = 'Hotdog',   defaultDuty = true, offDutyPay = false, grades = {['0'] = {name = 'Sales',      payment = 50}}},

	['police'] = {
		label = 'Law Enforcement', 
		type = "leo", 
		defaultDuty = true, 
		offDutyPay = false,
		grades = {
        	['0'] = {name = 'Cadet', payment = 600},
			['1'] = {name = 'Officer', payment = 800},
			['2'] = {name = 'Sergeant', payment = 1000},
			['3'] = {name = 'Leutenant', payment = 1300},
			['4'] = {name = 'Captain', isboss = true, payment = 1500},
			['5'] = {name = 'Chief of Police', isboss = true, payment = 2000},
        },
	},

	['fbi'] = {label = 'Federal Bureau of Investigation', type = "leo", defaultDuty = true, offDutyPay = false,
		grades = {
			['0'] = {name = 'Inferior Agent', payment = 600},
			['1'] = {name = 'Superior Agent', payment = 800},
			['2'] = {name = 'Special Agent', payment = 1200},
			['3'] = {name = 'Director of Bureau', isboss = true, payment = 2000},
		},
	},

	['ambulance'] = {label = 'EMS', type = 'ems', defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 150},
			['1'] = {name = 'Paramedic', payment = 225},
			['2'] = {name = 'Doctor', payment = 300},
			['3'] = {name = 'Surgeon', payment = 500},
			['4'] = {name = 'Co-Chief', payment = 600},
			['5'] = {name = 'Chief', isboss = true, payment = 700},
        },
	},
	['realestate'] = {label = 'Real Estate', defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'House Sales', payment = 75},
			['2'] = {name = 'Business Sales', payment = 100},
			['3'] = {name = 'Broker', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
	['taxi'] = {label = 'Taxi', defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Driver', payment = 75},
			['2'] = {name = 'Event Driver', payment = 100},
			['3'] = {name = 'Sales', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
	['cardealer'] = {label = 'Vehicle Dealer', defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Showroom Sales', payment = 75},
			['2'] = {name = 'Business Sales', payment = 100},
			['3'] = {name = 'Finance', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
	['mechanic'] = {label = 'LS Customs', type = "mechanic", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Novice', payment = 75},
			['2'] = {name = 'Experienced', payment = 100},
			['3'] = {name = 'Advanced', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
    ['mechanic2'] = {label = 'LS Customs', type = "mechanic", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Novice', payment = 75},
			['2'] = {name = 'Experienced', payment = 100},
			['3'] = {name = 'Advanced', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
    ['mechanic3'] = {label = 'LS Customs', type = "mechanic", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Novice', payment = 75},
			['2'] = {name = 'Experienced', payment = 100},
			['3'] = {name = 'Advanced', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
    ['beeker'] = {label = 'Beeker\'s Garage', type = "mechanic", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Novice', payment = 75},
			['2'] = {name = 'Experienced', payment = 100},
			['3'] = {name = 'Advanced', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
    ['bennys'] = {label = 'Benny\'s Original Motor Works', type = "mechanic", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'Recruit', payment = 50},
			['1'] = {name = 'Novice', payment = 75},
			['2'] = {name = 'Experienced', payment = 100},
			['3'] = {name = 'Advanced', payment = 125},
			['4'] = {name = 'Manager', isboss = true, payment = 150},
        },
	},
	['miner'] = {label = 'Miner', type = "miner", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'miner', payment = 50},
			['1'] = {name = 'miner2', payment = 75},
			['2'] = {name = 'miner3', payment = 100},
        },
	},
	['lumberjack'] = {label = 'Lumberjack', type = "lumberjack", defaultDuty = true, offDutyPay = false,
		grades = {
        	['0'] = {name = 'lumberjack', payment = 50},
			['1'] = {name = 'lumberjack2', payment = 75},
			['2'] = {name = 'lumberjack3', payment = 100},
        },
	},
	['wine'] = {label = 'Winery', type = "wine", defaultDuty = true, offDutyPay = false,
	grades = {
		['0'] = {name = 'wine', payment = 50},
		['1'] = {name = 'wine2', payment = 75},
		['2'] = {name = 'wine3', payment = 100},
		['3'] = {name = 'wine4', isboss = true, payment = 150},
	},
},
}